"""
Dummy practitioner data generator for testing SPRM
"""
from uuid import uuid4
from typing import List
import random

from algorithms.matching.models import (
    PractitionerProfile,
    TreatmentPhilosophy,
    CommunicationStyle
)


def generate_sample_practitioners() -> List[PractitionerProfile]:
    """Generate sample practitioner profiles"""

    # London coordinates
    base_lat = 51.5074
    base_lon = -0.1278

    practitioners = [
        PractitionerProfile(
            practitioner_id=uuid4(),
            full_name="Dr. Sarah Chen",
            business_name="Holistic Wellness London",
            specialties=["anxiety", "insomnia", "digestive_health"],
            primary_modalities=["herbal_medicine", "nutrition", "lifestyle_counseling"],
            target_domains=["emotional", "physical"],
            years_experience=12,
            credentials=["NIMH Registered Herbalist", "BSc Herbal Medicine", "MSc Nutrition"],
            professional_memberships=["NIMH", "BHMA"],
            verification_tier="gold",
            scvm_confidence_score=96.0,
            trust_score=96,
            treatment_philosophy=TreatmentPhilosophy.INTEGRATIVE,
            evidence_based=True,
            uses_interventions=["meditation", "ashwagandha", "yoga"],
            location_latitude=base_lat + random.uniform(-0.02, 0.02),
            location_longitude=base_lon + random.uniform(-0.02, 0.02),
            location_address="123 Harley Street, London",
            hourly_rate=85.0,
            session_duration_minutes=60,
            offers_sliding_scale=True,
            accepts_insurance=False,
            communication_style=CommunicationStyle.EDUCATIONAL,
            languages_spoken=["English", "Mandarin"],
            total_clients_treated=200,
            average_outcome_improvement=35.0,
            client_satisfaction_rating=4.8,
            bio="Registered herbalist with 12 years experience specializing in anxiety and sleep.",
            accepts_new_clients=True
        ),
        PractitionerProfile(
            practitioner_id=uuid4(),
            full_name="James Williams",
            business_name="Balance Acupuncture Clinic",
            specialties=["pain_management", "stress", "fertility"],
            primary_modalities=["acupuncture", "cupping", "chinese_herbs"],
            target_domains=["physical", "emotional"],
            years_experience=8,
            credentials=["BAcC Registered", "Lic.Ac.", "Diploma Chinese Herbal Medicine"],
            professional_memberships=["BAcC"],
            verification_tier="standard",
            scvm_confidence_score=92.0,
            trust_score=92,
            treatment_philosophy=TreatmentPhilosophy.TRADITIONAL,
            evidence_based=True,
            uses_interventions=["acupuncture"],
            location_latitude=base_lat + random.uniform(-0.02, 0.02),
            location_longitude=base_lon + random.uniform(-0.02, 0.02),
            location_address="45 Camden High Street, London",
            hourly_rate=75.0,
            session_duration_minutes=60,
            offers_sliding_scale=False,
            accepts_insurance=True,
            communication_style=CommunicationStyle.DIRECT,
            languages_spoken=["English"],
            total_clients_treated=150,
            average_outcome_improvement=28.0,
            client_satisfaction_rating=4.6,
            bio="Licensed acupuncturist specializing in pain management and stress relief.",
            accepts_new_clients=True
        ),
        PractitionerProfile(
            practitioner_id=uuid4(),
            full_name="Emma Thompson",
            business_name="Nourish Nutrition",
            specialties=["weight_management", "digestive_health", "energy"],
            primary_modalities=["nutrition", "functional_medicine", "supplement_guidance"],
            target_domains=["physical"],
            years_experience=5,
            credentials=["Registered Nutritionist", "BSc Nutrition", "CNHC Registered"],
            professional_memberships=["CNHC", "AfN"],
            verification_tier="standard",
            scvm_confidence_score=89.0,
            trust_score=89,
            treatment_philosophy=TreatmentPhilosophy.EVIDENCE_BASED,
            evidence_based=True,
            uses_interventions=["omega3", "nutrition"],
            location_latitude=base_lat + random.uniform(-0.02, 0.02),
            location_longitude=base_lon + random.uniform(-0.02, 0.02),
            location_address="78 King's Road, Chelsea",
            hourly_rate=70.0,
            session_duration_minutes=60,
            offers_sliding_scale=True,
            accepts_insurance=False,
            communication_style=CommunicationStyle.DIRECT,
            languages_spoken=["English"],
            total_clients_treated=100,
            average_outcome_improvement=30.0,
            client_satisfaction_rating=4.7,
            bio="Evidence-based nutritionist helping clients optimize health through diet.",
            accepts_new_clients=True
        ),
        PractitionerProfile(
            practitioner_id=uuid4(),
            full_name="Priya Sharma",
            business_name="Mindful Movement Studio",
            specialties=["anxiety", "stress", "chronic_pain"],
            primary_modalities=["yoga_therapy", "meditation", "breathwork"],
            target_domains=["emotional", "physical", "spiritual"],
            years_experience=10,
            credentials=["Certified Yoga Therapist", "E-RYT 500", "Meditation Teacher"],
            professional_memberships=["IAYT", "Yoga Alliance"],
            verification_tier="gold",
            scvm_confidence_score=94.0,
            trust_score=94,
            treatment_philosophy=TreatmentPhilosophy.HOLISTIC,
            evidence_based=True,
            uses_interventions=["yoga", "meditation"],
            location_latitude=base_lat + random.uniform(-0.02, 0.02),
            location_longitude=base_lon + random.uniform(-0.02, 0.02),
            location_address="12 Notting Hill Gate, London",
            hourly_rate=65.0,
            session_duration_minutes=75,
            offers_sliding_scale=True,
            accepts_insurance=False,
            communication_style=CommunicationStyle.WARM,
            languages_spoken=["English", "Hindi"],
            total_clients_treated=180,
            average_outcome_improvement=32.0,
            client_satisfaction_rating=4.9,
            bio="Certified yoga therapist with focus on anxiety, stress, and chronic pain relief.",
            accepts_new_clients=True
        ),
        PractitionerProfile(
            practitioner_id=uuid4(),
            full_name="Dr. Michael Brown",
            business_name="Integrative Mind Clinic",
            specialties=["anxiety", "depression", "trauma"],
            primary_modalities=["cbt", "mindfulness", "somatic_therapy"],
            target_domains=["emotional", "cognitive"],
            years_experience=15,
            credentials=["Clinical Psychologist", "CBT Certified", "PhD Psychology"],
            professional_memberships=["BPS", "BABCP"],
            verification_tier="gold",
            scvm_confidence_score=98.0,
            trust_score=98,
            treatment_philosophy=TreatmentPhilosophy.INTEGRATIVE,
            evidence_based=True,
            uses_interventions=["cbt", "meditation"],
            location_latitude=base_lat + random.uniform(-0.02, 0.02),
            location_longitude=base_lon + random.uniform(-0.02, 0.02),
            location_address="56 Harley Street, London",
            hourly_rate=120.0,
            session_duration_minutes=50,
            offers_sliding_scale=False,
            accepts_insurance=True,
            communication_style=CommunicationStyle.COLLABORATIVE,
            languages_spoken=["English"],
            total_clients_treated=300,
            average_outcome_improvement=40.0,
            client_satisfaction_rating=4.9,
            bio="Clinical psychologist integrating evidence-based therapy with mindfulness.",
            accepts_new_clients=True
        ),
    ]

    return practitioners
